### ISSUE TITLE
How to restart CI?

### ISSUE THREAD

**Issue by johanneskoester** [conda-forge/cairosvg-feedstock#1]
@ocefpaf sorry to bother you again. The dependencies are built, but I am unsure how to restart the CIs for this feedstock. At least travis is not yet initialized apparently, so it asks me for a commit. Is there a way to trigger it without committing something senseless to the repo?

**Comment by johanneskoester** [comment]
Solved. I figured out that I can use conda-smithy to do this.

**Comment by ocefpaf** [comment]
> @ocefpaf sorry to bother you again.

No problem. But sometimes it will be faster for you to reach me via gitter: https://gitter.im/conda-forge/conda-forge.github.io

Glad you figure it out!

> Is there a way to trigger it without committing something senseless to the repo?

You should be able to restart Travis-CI via Travis web interface. But it may take a while for the repo to appear in your list. You can force it to sync though.
