### ISSUE TITLE
feature request: enabling build for Windows

### ISSUE THREAD

**Issue by pharshalp** [conda-forge/cairosvg-feedstock#14]
Is there a plan to enable a build for Windows?

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by carlodri** [comment]
I will try to take a look, but I cannot promise to do it very soon..

**Comment by carlodri** [comment]
@pharshalp working on it here: https://github.com/conda-forge/cairocffi-feedstock/pull/11

would be happy to have your feedback/contributions since I'm not a cairo user myself... thanks!

**Comment by pharshalp** [comment]
Thanks! I will try it out and give feedback. I wish I could help in the build process but I do not believe I have the necessary expertise.

**Comment by carlodri** [comment]
@pharshalp no worries, also testing helps a lot! Let me know if it works for you.

**Comment by carlodri** [comment]
@pharshalp could you please give me a feedback if the current windows build works?

**Comment by pharshalp** [comment]
@carlodri v2.3 wasn't working properly. I will try the latest version tomorrow and post the error I was getting (if I still face the same issue as for v2.3).

**Comment by pharshalp** [comment]
@carlodri 
**I can confirm that v2.3.1 seems to be working fine! Thanks for fixing that!**

v2.3 had some issues [it was raising `URLError(exp)` from urllib)]
```
File "C:\Users\USERNAME\AppData\Local\Continuum\miniconda3\envs\svgutils\lib\urllib\request.py", line 1490, in open_local_file
    raise URLError(exp)
urllib.error.URLError: <urlopen error [WinError 2] The system cannot find the file specified: 'C:\\Users\\USERNAME\\MYPROJECTPATH\\%23glyph0-1'>
```

**Comment by carlodri** [comment]
@pharshalp thanks for the feedback! Can you show me which commands/scripts you use for testing? It might be useful to put them in the package test suite. For instance, which is the command that fails in v2.3?

Thanks!

**Comment by pharshalp** [comment]
@carlodri  a bit busy right now... in a week or two I will turn my use-case into a test and post it here. Thanks!

**Comment by carlodri** [comment]
@pharshalp great thanks!
