### ISSUE TITLE
Python 3.6 build for linux-64

### ISSUE THREAD

**Issue by jonmmease** [conda-forge/cairosvg-feedstock#6]
Hi, thanks for putting this feedstock together.

I'd like to use this package from Python 3.6 on Linux, but from https://anaconda.org/conda-forge/cairosvg/files it looks like the Python 3.6 version is only built for OS X. 

What would it take to build this for Linux 64 as well?

Thanks!

**Comment by carlodri** [comment]
@jonmmease can this be closed?

**Comment by jonmmease** [comment]
Yes, looks like the Linux builds are there now. Thanks!
